# Generated by Django 2.2.3 on 2019-07-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190711_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
