# Generated by Django 2.2.3 on 2019-07-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190712_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
