# Generated by Django 2.2.5 on 2019-10-01 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('name',), 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
