# Generated by Django 2.2.5 on 2019-12-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191203_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdocument',
            name='document',
            field=models.FileField(upload_to='files/'),
        ),
    ]
